#!/bin/bash

# Fetch CA Certificate Script
# Downloads the root CA certificate and generates ca-certs.h for the active project.
#
# By default fetches ISRG Root X1 (Let's Encrypt) used by HiveMQ Cloud.
# Override by passing a URL: ./scripts/fetch-ca-cert.sh --url https://example.com/ca.pem

set -e

# Save original args before _resolve_project.sh consumes them via shift
ORIG_ARGS=("$@")

# Resolve project
source "$(dirname "$0")/_resolve_project.sh"

# Parse --url from saved args
CERT_URL="https://letsencrypt.org/certs/isrgrootx1.pem"
i=0
while [ $i -lt ${#ORIG_ARGS[@]} ]; do
  case "${ORIG_ARGS[$i]}" in
    --url)
      CERT_URL="${ORIG_ARGS[$((i+1))]}"
      i=$((i+2))
      ;;
    *)
      i=$((i+1))
      ;;
  esac
done

OUTPUT_FILE="$PROJECT_DIR/ca-certs.h"

echo "🔐 Fetching CA Certificate"
echo "=========================="
echo "   Project: $PROJECT_NAME"
echo "   Source:  $CERT_URL"
echo "   Output:  $OUTPUT_FILE"
echo ""

# Download the PEM certificate
echo "📥 Downloading certificate..."
PEM_CONTENT=$(curl -sS --fail "$CERT_URL")

if [ -z "$PEM_CONTENT" ]; then
  echo "❌ Failed to download certificate from $CERT_URL"
  exit 1
fi

# Verify it looks like a PEM certificate
if ! echo "$PEM_CONTENT" | grep -q "BEGIN CERTIFICATE"; then
  echo "❌ Downloaded content does not appear to be a PEM certificate"
  exit 1
fi

# Extract just the PEM block (in case the file has extra metadata)
PEM_BLOCK=$(echo "$PEM_CONTENT" | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p')

echo "✅ Certificate downloaded"

# Generate the header file
cat > "$OUTPUT_FILE" << HEADER_EOF
// Auto-generated by scripts/fetch-ca-cert.sh
// Source: $CERT_URL
// Re-run the script to update: ./scripts/fetch-ca-cert.sh --project $PROJECT_NAME

#ifndef CA_CERTS_H
#define CA_CERTS_H

static const char ROOT_CA_CERT[] = R"(
$PEM_BLOCK
)";

#endif
HEADER_EOF

echo "✅ Generated $OUTPUT_FILE"
echo ""
echo "🎉 Done! Your project can now #include \"ca-certs.h\" and use ROOT_CA_CERT."
