# Generated by Django 5.0.4 on 2024-04-07 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="api_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
