# Generated by Django 5.0.4 on 2024-04-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taps", "0002_device_api_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tap",
            old_name="target",
            new_name="device",
        ),
    ]
