name: jira-utils CI
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install tools
        run: |
          pipx install poethepoet
          pipx install pre-commit

      - name: Set up project
        working-directory: ./jira-utils
        run: poe configure

      - name: Run tests
        working-directory: ./jira-utils
        run: poe test-full

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./jira-utils/coverage.xml
          flags: jira-utils
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run lint
        working-directory: ./jira-utils
        run: poe lint

      - name: Run hooks
        working-directory: ./jira-utils
        run: poe hooks-run
